apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- rollout.yaml
- service.yaml
- preview-service.yaml
images:
- name: schoolofdevops/vote
  newName: prabhatsingh014/vote
  newTag: v1
